### ISSUE TITLE
getSession fails when req.headers.cookie are undefined

### ISSUE THREAD

**Issue by Romstar** [iaincollins/next-auth#319] opened 2020-06-23 23:22 UTC
**Describe the bug**
getSession({req}) throws an error rather than returning undefined when req.headers.cookie is undefined.

**To Reproduce**
1. Call getSession({req}) when req.headers.cookie is **undefined**

**Expected behavior**
an undefined object should be returned from the _getSession({req})_ function call.

**Screenshots or error logs**
[next-auth][error][CLIENT_FETCH_ERROR] [
  'null/session',
  TypeError: Only absolute URLs are supported

* [x] Found the source code helpful

**Comment by iaincollins** [comment] 2020-06-23 23:59
This looks like a duplicate of #299 and #313.

Details of a beta release with changes to resolve this can be found in #315

**Closed by iaincollins** 2020-06-23 23:59 UTC
Labels: bug, duplicate
