### ISSUE TITLE
Customized errors instead of showing server configuration error on wrong credentials

### ISSUE THREAD

**Issue by Jones3106** [iaincollins/next-auth#476] opened 2020-07-25 06:16 UTC
**Your question**
Is there any way to display custom errors like "Invalid password" instead of the default server configuration error on wrong credentials

**What are you trying to do**
I'm trying to show an error like "Invalid password" or "Unknown account" on credentials login instead of the default server configuration error. I have tried using `throw 'Invalid Password'` and `throw { error: 'Invalid Password' }` instead of `Promise.Resolve(null)` but it doesn't seems to work. Can anyone point me in the right direction?

**Documentation feedback**
* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by jemmyphan** [comment] 2020-07-25 15:10
seems like duplicate of https://github.com/iaincollins/next-auth/issues/413.

**Closed** 2020-07-25 16:59 UTC
Labels: question
