### ISSUE TITLE
Improved error handling

### ISSUE THREAD

**Issue by adeshkumar1201** [iaincollins/next-auth#98] opened 2020-04-21 09:13 UTC
Thanks for the update. I was hesitant to access the next-auth routes manually but was able to signin as you suggested above successfully.

One follow-up question, though. Is there a way to capture errors thrown in the next-auth.functions signin() method? For example, if signin() fails, next-auth redirects to error.js and passes '/auth/error?action=signin&type=credentials' in the query string. Is there a way to capture more detailed information regarding the failure - perhaps the error originally thrown during signin()??

_Originally posted by @DomenicoCammarota in https://github.com/iaincollins/next-auth/issues/45#issuecomment-417373260_

**Comment by iaincollins** [comment] 2020-05-03 16:30
Hi @adeshkumar1201,

Short answer, no there isn't. 

I've just made [an announcement about version 2.0](#99) which should drop later this month.

It's much simpler to configure and this is definitely something that should be address in 2.x - if not at release, then it should be on the roadmap for 2.1.

**Comment by iaincollins** [comment] 2020-05-09 12:45
Moving this into version 2.0 milestone as this needs to be addressed.

There is a chance this will slip into a subsequent release (e.g. v2.1) but the issue is still relevant.

**Comment by ndom91** [comment] 2020-06-06 18:20
@iaincollins I saw you mention somewhere you'd like to have URLs to the docs in the error messages. I like this idea a lot too and I noticed you have error codes for most things already built in (i.e. CLIENT_USE_SESSION_ERROR.) 

Maybe we could use redirects to get those error messages to point to the right page, i.e. `next-auth.js.org/err/CLIENT_USE_SESSION_ERROR` could point to the client page. And we could append these to the end of the error output on the console. 

If your into the idea, I could take a look at this a little further.

**Comment by iaincollins** [comment] 2020-06-06 18:46
Yes, I would love that! I am a huge fan of errors that point to a URL.

Maybe we could even make specific docs for each error so they are easy to link to and describe?

e.g.

`https://next-auth.js.org/errors/CLIENT_USE_SESSION_ERROR` -> `www/docs/errors/CLIENT_USE_SESSION_ERROR.md`?

Or I guess we could just have a single page for all errors and use anchor links, if that approach feels like overkill?

e.g.

`https://next-auth.js.org/errors#CLIENT_USE_SESSION_ERROR`

Either would be better than no documentation :D

**Comment by ndom91** [comment] 2020-06-08 16:14
Okay so this has been added with #222, however @iaincollins I just wanted to remind you, the errors docs page needs filling out eventually. Currently I only have one of the errors descriptions written out. 

I've gathered all the named errors I could find in the application in the document already, they just need descriptions now. See: https://next-auth.js.org/errors or `www/docs/errors.md`. Some of them are pretty obvious as to what the error is and I can help you write those, but others you're going to have to decipher haha

**Comment by iaincollins** [comment] 2020-06-08 16:22
@ndom91 Oh no how is `_GET_OAUTH_ACCESS_TOKEN_ERROR` a real error 🙈

That list is great, thank you! I guess I have some cleaning up and documenting to do. :-)

**Comment by iaincollins** [comment] 2020-06-14 23:06
We have excellent debug logging, a place for online documentation (and integration that directs users to the website when an error is logged) as well as new events system (which is great for audit logging), so I'm going to close this off as resolved.

We still need to expand on some of the errors and provide additional debug logging, but we now have the mechanisms to do that easily.

**Closed by iaincollins** 2020-06-14 23:06 UTC
Labels: enhancement, question
