### ISSUE TITLE
How to pass option to set raw-body limit?

### ISSUE THREAD

**Issue by jenssogaard** [iaincollins/next-auth#44] opened 2018-08-28 02:15 UTC
Is it possible to pass down options to raw-body? Currently stuck on the 100kb default limit.

**Comment by iaincollins** [comment] 2018-08-29 15:42
Thanks for the issue.

Doh! Is this a default limit on the body of POST submissions? (Is it is low as that? Ouch.)

That should be no problem to fix. If you have any copy/paste bits of the relevant config, link to docs or a rough example of how to set it so that that we can expose it as an option that would be most helpful to save me looking up / adding the wrong thing as I seem to vaguely recall there are at least a couple of options that related to max POST size.

**Comment by jenssogaard** [comment] 2018-09-27 15:05
Hi @iaincollins. Just created a simple PR that solves this. It's tried and tested. I hope you can merge soon 👍

**Comment by jenssogaard** [comment] 2018-10-01 13:13
Hi @iaincollins. Do you have time to have a look at [my PR that solves this](https://github.com/iaincollins/next-auth/pull/52)? Do you need help/contributors on this project? I'll be happy to assist.

**Comment by jenssogaard** [comment] 2018-10-02 00:28
@iaincollins it's not urgent. But I wouldn't mind a push to NPM soon 😄

**Comment by jenssogaard** [comment] 2018-10-30 13:09
@iaincollins can you release the minor update soon?

**Comment by iaincollins** [comment] 2020-05-09 13:01
Thank you for the update and sorry there ended up being no more updates to 1.x in NPM - I was super busy for a while and didn't have the time.

Hopefully this won't be an issue in the [upcoming release of 2.0](#99), which doesn't rely on Express, so I think it's safe to close this off now.

**Closed by iaincollins** 2020-05-09 13:01 UTC
Labels: bug, enhancement

**Comment by SaraVieira** [comment] 2021-03-19 18:47
Hey!

Sorry for reopening such an old issue, I am trying to allow users top change their profile image and sending a base64 of the image and I think it reaches this issue.

The person logs in no problem in the backend but the session is never set probably because it hits this

**Comment by balazsorban44** [comment] 2021-03-19 22:43
hi @SaraVieira, I suggest you open a new issue with a reproduction if you have some problems

**Comment by SaraVieira** [comment] 2021-03-24 15:17
Hey!

That makes sense, it's hard to reproduce in a small project.

Will try to do it today, if I don't ignore it because it's not that important
